#!/bin/bash
source ./demo-magic.sh
# text color
DEMO_CMD_COLOR=$WHITE
# hide the evidence
clear

#!/bin/bash

mkdir -p ~/.local/bin
export PATH=~/.local/bin:$PATH
cat <<- "EOF" > ~/.local/bin/show
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
echo "${green}--- app.py ---${reset}" && cat app.py && echo "${green}--- requirements.txt ---${reset}" && cat requirements.txt && echo "${green}--- Dockerfile ---${reset}" && cat Dockerfile
EOF

chmod +x ~/.local/bin/show
pe "show"
pe "docker build -t demo ."
pe "dive demo"
